# Generated by Django 2.0.5 on 2018-05-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=100)),
                ('original_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_state', to='bot.State')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_state', to='bot.State')),
            ],
        ),
    ]
